import { defineType, defineField, defineArrayMember } from 'sanity';

export const program = defineType({
  name: 'program',
  title: 'Program',
  type: 'document',
  fields: [
    defineField({
      name: 'id',
      type: 'slug',
      title: 'ID / Slug',
      description: 'URL-safe identifier, e.g. ai-mastery-bootcamp',
      options: { source: 'titleEn' },
      validation: (R) => R.required(),
    }),
    defineField({ name: 'titleEn', type: 'string', title: 'Title (EN)', validation: (R) => R.required() }),
    defineField({ name: 'titleAr', type: 'string', title: 'Title (AR)', validation: (R) => R.required() }),
    defineField({ name: 'descriptionEn', type: 'text', title: 'Short Description (EN)', rows: 3 }),
    defineField({ name: 'descriptionAr', type: 'text', title: 'Short Description (AR)', rows: 3 }),
    defineField({
      name: 'category',
      type: 'string',
      title: 'Category',
      options: { list: ['ai', 'business', 'certification', 'corporate'], layout: 'radio' },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'level',
      type: 'string',
      title: 'Level',
      options: { list: ['beginner', 'intermediate', 'advanced'], layout: 'radio' },
      validation: (R) => R.required(),
    }),
    defineField({ name: 'duration', type: 'string', title: 'Duration (EN)', description: 'e.g. 12 Weeks' }),
    defineField({ name: 'durationAr', type: 'string', title: 'Duration (AR)' }),
    defineField({ name: 'format', type: 'string', title: 'Format (EN)', description: 'e.g. Hybrid (Online + In-Person)' }),
    defineField({ name: 'formatAr', type: 'string', title: 'Format (AR)' }),
    defineField({ name: 'overviewEn', type: 'text', title: 'Overview (EN)', rows: 5 }),
    defineField({ name: 'overviewAr', type: 'text', title: 'Overview (AR)', rows: 5 }),
    defineField({
      name: 'outcomesEn',
      type: 'array',
      title: 'Learning Outcomes (EN)',
      of: [defineArrayMember({ type: 'string' })],
    }),
    defineField({
      name: 'outcomesAr',
      type: 'array',
      title: 'Learning Outcomes (AR)',
      of: [defineArrayMember({ type: 'string' })],
    }),
    defineField({
      name: 'modulesEn',
      type: 'array',
      title: 'Curriculum Modules (EN)',
      of: [defineArrayMember({ type: 'bilingualModule' })],
    }),
    defineField({
      name: 'modulesAr',
      type: 'array',
      title: 'Curriculum Modules (AR)',
      of: [defineArrayMember({ type: 'bilingualModule' })],
    }),
    defineField({ name: 'instructorEn', type: 'bilingualInstructor', title: 'Instructor (EN)' }),
    defineField({ name: 'instructorAr', type: 'bilingualInstructor', title: 'Instructor (AR)' }),
    defineField({ name: 'certificationEn', type: 'text', title: 'Certification Info (EN)', rows: 3 }),
    defineField({ name: 'certificationAr', type: 'text', title: 'Certification Info (AR)', rows: 3 }),
    defineField({
      name: 'faqEn',
      type: 'array',
      title: 'FAQ (EN)',
      of: [defineArrayMember({ type: 'bilingualFaq' })],
    }),
    defineField({
      name: 'faqAr',
      type: 'array',
      title: 'FAQ (AR)',
      of: [defineArrayMember({ type: 'bilingualFaq' })],
    }),
    defineField({
      name: 'icon',
      type: 'string',
      title: 'Icon Name',
      description: 'Lucide icon name: Brain, Award, Users, BarChart3, Shield, Cloud',
    }),
    defineField({
      name: 'order',
      type: 'number',
      title: 'Sort Order',
      description: 'Lower numbers appear first in the listing',
    }),
  ],
  orderings: [
    { title: 'Sort Order', name: 'orderAsc', by: [{ field: 'order', direction: 'asc' }] },
  ],
  preview: {
    select: { title: 'titleEn', subtitle: 'category' },
  },
});
